### ISSUE TITLE
validate date field

### ISSUE THREAD

**Issue by jakehobbs** [dxe/adb#10]
Safari (non-mobile) lets you type whatever you want into it.

**Comment by mleanos** [comment]
Is this still an issue?

**Comment by jakehobbs** [comment]
Maybe just making the error message more clear for end-users is all we need to do:

<img width="477" alt="screen shot 2018-12-27 at 8 41 24 am" src="https://user-images.githubusercontent.com/23712446/50487440-4866bf80-09b3-11e9-85a8-3b6229b80b3d.png">

**Comment by jakehobbs** [comment]
Safari now shows a date picker, so the current implementation is fine.
