### ISSUE TITLE
Allow local development w/o an Internet connection

### ISSUE THREAD

**Issue by jakehobbs** [dxe/adb#135]
It's not currently possible to do local development without an Internet connection due to the below error.
```
Get "https://accounts.google.com/.well-known/openid-configuration": dial tcp: lookup accounts.google.com: no such host
```
It would be useful to be able to work on the ADB when no Internet connection is available (i.e. on a train, plane, etc.).

**Comment by AlexisDeschamps** [comment]
This should be partially fixed after https://github.com/dxe/adb/pull/152. There might be features that still don't work with an online connection so feel free to reopen this issue.
