### ISSUE TITLE
"make dev_db" is out of date

### ISSUE THREAD

**Issue by mdempsky** [dxe/adb#30]
It looks like we've added some new tables and columns, but not updated model/db.go's WipeDatabase function.

/cc @jakehobbs

**Comment by mdempsky** [comment]
Here are the tables as they currently exist in the production database:

    mysql> describe activists;
    +-------------------------+--------------+------+-----+-----------+----------------+
    | Field                   | Type         | Null | Key | Default   | Extra          |
    +-------------------------+--------------+------+-----+-----------+----------------+
    | id                      | int(11)      | NO   | PRI | NULL      | auto_increment |
    | name                    | varchar(80)  | NO   | UNI | NULL      |                |
    | email                   | varchar(80)  | NO   |     |           |                |
    | phone                   | varchar(20)  | NO   |     |           |                |
    | location                | varchar(200) | YES  |     |           |                |
    | facebook                | varchar(200) | NO   |     |           |                |
    | activist_level          | varchar(40)  | NO   |     | Supporter |                |
    | hidden                  | tinyint(1)   | NO   |     | 0         |                |
    | connector               | varchar(100) | NO   |     |           |                |
    | contacted_date          | varchar(20)  | NO   |     |           |                |
    | interested              | varchar(5)   | NO   |     |           |                |
    | meeting_date            | varchar(20)  | NO   |     |           |                |
    | escalation              | varchar(5)   | NO   |     |           |                |
    | source                  | varchar(255) | NO   |     |           |                |
    | date_organizer          | date         | YES  |     | NULL      |                |
    | date_senior_organizer   | date         | YES  |     | NULL      |                |
    | dob                     | text         | YES  |     | NULL      |                |
    | training0               | varchar(20)  | YES  |     | NULL      |                |
    | training1               | varchar(20)  | YES  |     | NULL      |                |
    | training2               | varchar(20)  | YES  |     | NULL      |                |
    | training3               | varchar(20)  | YES  |     | NULL      |                |
    | training4               | varchar(20)  | YES  |     | NULL      |                |
    | training5               | varchar(20)  | YES  |     | NULL      |                |
    | training6               | varchar(20)  | YES  |     | NULL      |                |
    | prospect_organizer      | tinyint(1)   | NO   |     | 0         |                |
    | prospect_chapter_member | tinyint(4)   | NO   |     | 0         |                |
    | prospect_circle_member  | tinyint(4)   | NO   |     | 0         |                |
    | dev_manager             | varchar(100) | NO   |     |           |                |
    | dev_interest            | varchar(200) | NO   |     |           |                |
    | dev_auth                | varchar(20)  | YES  |     | NULL      |                |
    | dev_email_sent          | varchar(20)  | YES  |     | NULL      |                |
    | dev_vetted              | tinyint(1)   | NO   |     | 0         |                |
    | dev_interview           | varchar(20)  | YES  |     | NULL      |                |
    | dev_onboarding          | tinyint(1)   | NO   |     | 0         |                |
    | dev_application_date    | date         | YES  |     | NULL      |                |
    | cm_first_email          | varchar(20)  | YES  |     | NULL      |                |
    | cm_approval_email       | varchar(20)  | YES  |     | NULL      |                |
    | cm_warning_email        | varchar(20)  | YES  |     | NULL      |                |
    | cir_first_email         | varchar(20)  | YES  |     | NULL      |                |
    +-------------------------+--------------+------+-----+-----------+----------------+
    39 rows in set (0.00 sec)
    
    mysql> describe adb_users;
    +----------+-------------+------+-----+---------+----------------+
    | Field    | Type        | Null | Key | Default | Extra          |
    +----------+-------------+------+-----+---------+----------------+
    | id       | int(11)     | NO   | PRI | NULL    | auto_increment |
    | email    | varchar(60) | NO   |     | NULL    |                |
    | admin    | tinyint(1)  | NO   |     | 0       |                |
    | disabled | tinyint(1)  | NO   |     | 0       |                |
    +----------+-------------+------+-----+---------+----------------+
    4 rows in set (0.00 sec)
    
    mysql> describe circles;
    +------------------+--------------+------+-----+---------+----------------+
    | Field            | Type         | Null | Key | Default | Extra          |
    +------------------+--------------+------+-----+---------+----------------+
    | id               | int(11)      | NO   | PRI | NULL    | auto_increment |
    | name             | varchar(60)  | NO   | UNI | NULL    |                |
    | type             | tinyint(1)   | NO   |     | NULL    |                |
    | group_email      | varchar(100) | NO   |     | 1       |                |
    | visible          | tinyint(1)   | NO   |     | 1       |                |
    | description      | text         | NO   |     | NULL    |                |
    | meeting_time     | text         | NO   |     | NULL    |                |
    | meeting_location | text         | NO   |     | NULL    |                |
    | coords           | text         | NO   |     | NULL    |                |
    +------------------+--------------+------+-----+---------+----------------+
    9 rows in set (0.00 sec)
    
    mysql> describe circle_members;
    +----------------------------+------------+------+-----+---------+-------+
    | Field                      | Type       | Null | Key | Default | Extra |
    +----------------------------+------------+------+-----+---------+-------+
    | circle_id                  | int(11)    | NO   | PRI | NULL    |       |
    | activist_id                | int(11)    | NO   | PRI | NULL    |       |
    | point_person               | tinyint(4) | NO   |     | 0       |       |
    | non_member_on_mailing_list | tinyint(4) | NO   |     | 0       |       |
    +----------------------------+------------+------+-----+---------+-------+
    4 rows in set (0.00 sec)
    
    mysql> describe events;
    +------------+-------------+------+-----+---------+----------------+
    | Field      | Type        | Null | Key | Default | Extra          |
    +------------+-------------+------+-----+---------+----------------+
    | id         | int(11)     | NO   | PRI | NULL    | auto_increment |
    | name       | varchar(60) | NO   | MUL | NULL    |                |
    | date       | date        | NO   | MUL | NULL    |                |
    | event_type | varchar(60) | NO   |     | NULL    |                |
    +------------+-------------+------+-----+---------+----------------+
    4 rows in set (0.00 sec)
    
    mysql> describe event_attendance;
    +-------------+---------+------+-----+---------+-------+
    | Field       | Type    | Null | Key | Default | Extra |
    +-------------+---------+------+-----+---------+-------+
    | activist_id | int(11) | NO   | PRI | NULL    |       |
    | event_id    | int(11) | NO   | PRI | NULL    |       |
    +-------------+---------+------+-----+---------+-------+
    2 rows in set (0.00 sec)
    
    mysql> describe merged_activist_attendance;
    +-------------------------------+------------+------+-----+---------+-------+
    | Field                         | Type       | Null | Key | Default | Extra |
    +-------------------------------+------------+------+-----+---------+-------+
    | original_activist_id          | int(11)    | NO   | PRI | NULL    |       |
    | target_activist_id            | int(11)    | NO   | PRI | NULL    |       |
    | event_id                      | int(11)    | NO   | PRI | NULL    |       |
    | replaced_with_target_activist | tinyint(1) | NO   |     | NULL    |       |
    +-------------------------------+------------+------+-----+---------+-------+
    4 rows in set (0.00 sec)
    
    mysql> describe working_groups;
    +------------------+--------------+------+-----+---------+----------------+
    | Field            | Type         | Null | Key | Default | Extra          |
    +------------------+--------------+------+-----+---------+----------------+
    | id               | int(11)      | NO   | PRI | NULL    | auto_increment |
    | name             | varchar(60)  | NO   | UNI | NULL    |                |
    | type             | tinyint(1)   | NO   |     | NULL    |                |
    | group_email      | varchar(100) | NO   |     | NULL    |                |
    | visible          | tinyint(1)   | NO   |     | 0       |                |
    | description      | text         | NO   |     | NULL    |                |
    | meeting_time     | text         | NO   |     | NULL    |                |
    | meeting_location | text         | NO   |     | NULL    |                |
    | coords           | text         | NO   |     | NULL    |                |
    +------------------+--------------+------+-----+---------+----------------+
    9 rows in set (0.00 sec)
    
    mysql> describe working_group_members;
    +----------------------------+------------+------+-----+---------+-------+
    | Field                      | Type       | Null | Key | Default | Extra |
    +----------------------------+------------+------+-----+---------+-------+
    | working_group_id           | int(11)    | NO   | PRI | NULL    |       |
    | activist_id                | int(11)    | NO   | PRI | NULL    |       |
    | point_person               | tinyint(4) | NO   |     | 0       |       |
    | non_member_on_mailing_list | tinyint(4) | NO   |     | 0       |       |
    +----------------------------+------------+------+-----+---------+-------+
    4 rows in set (0.00 sec)

**Comment by mdempsky** [comment]
Actually, `show create table` is way better than `describe': it shows the exact `create table` command to recreate it:

    CREATE TABLE `events` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `name` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL,
      `date` date NOT NULL,
      `event_type` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL,
      PRIMARY KEY (`id`),
      KEY `date_name` (`date`,`name`),
      FULLTEXT KEY `name` (`name`)
    ) ENGINE=InnoDB AUTO_INCREMENT=3220 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci

We can probably omit a lot of the defaults in db.go though.

**Comment by jakehobbs** [comment]
Thanks!
