### ISSUE TITLE
ActivistList.vue's "view" property validator out of date

### ISSUE THREAD

**Issue by mdempsky** [dxe/adb#37]
In a dev build, navigating to http://localhost:8080/chapter_member_prospects shows this error in the JavaScript console:

    [Vue warn]: Invalid prop: custom validator check failed for prop "view".
    
    found in
    
    ---> <ActivistList> at frontend/ActivistList.vue
           <Root>

This is because "chapter_member_prospects" isn't recognized by the props validator logic at https://github.com/dxe/adb/blob/74743ba7c89a7fd9e214d75950dc24629570187b/frontend/ActivistList.vue#L856. There are probably others that are missing too.

This doesn't seem to have any practical consequences though. It doesn't even show up in production builds.

Originally pointed out by @mleanos at https://github.com/dxe/adb/pull/32#pullrequestreview-187772333

**Comment by jakehobbs** [comment]
No longer an issue.
