### ISSUE TITLE
Improve user access: add "name" column for tracking & create "events only" role

### ISSUE THREAD

**Issue by mleanos** [dxe/adb#38]
Currently, ADB users are either an "admin" or not. Any user who is not an admin can access every view of the application, other than the Users section. In most cases users are given access to ADB for taking attendance and don't need access to the other areas of the application; in particular the Activists data can contain sensitive information that not everyone needs access to.

We should create additional user "roles" (or simple flags) to restrict access to individual areas of the application. For instance, we might just want to give most users a "attendance" role and only give them access to the Events section for adding event attendance.

**Comment by mdempsky** [comment]
I think this is done now.
