### ISSUE TITLE
Change "hide activist" to "delete activist"

### ISSUE THREAD

**Issue by jakehobbs** [dxe/adb#68]
We never do anything with "hidden" activists. This will make reporting easier.

**Comment by AlexisDeschamps** [comment]
@jakehobbs It seems the `hide-activist-modal` modal is not accessible. Is this accurate? Would the idea be to completely remove it and add similar "delete activist" functionality?

**Comment by jakehobbs** [comment]
Currently there is just a "merge activist" option, which hides one activist and merges their information into the "merge winner." I think we can just delete the "merge loser" instead of hiding them. (If there is any objection to that, then maybe we could create a new "deleted_activists" table that we move the deleted people to. Then we can remove all of the hidden activists who are currently in activists table. This will make reporting easier since people won't need to remember to add "where hidden = 0" whenever writing queries for reports.

**Comment by jakehobbs** [comment]
Or we could just write a row to the activists_history table that contains a record of the delete operation and not make a entirely new table.

**Comment by jakehobbs** [comment]
Let me know if that makes sense. Feel free to push back if you think that sounds like it's against best practices or if you have a better idea.

**Comment by jakehobbs** [comment]
This is very low priority and may not need to be done.

**Comment by jakehobbs** [comment]
Closing this for now as it may have unintended side effects.
