### ISSUE TITLE
Add "number of people" to new event and events list

### ISSUE THREAD

**Issue by samertm** [dxe/adb#8]

**Comment by mleanos** [comment]
Is this referring to the "attendance" displayed on these views? If so, it's there already 🎉 

![image](https://user-images.githubusercontent.com/5613734/30620132-48052ca2-9d58-11e7-9e91-c70da6ff2569.png)

![image](https://user-images.githubusercontent.com/5613734/30620142-53fb469a-9d58-11e7-8d73-cb87041b90a6.png)

**Comment by samertm** [comment]
Yup!
