### ISSUE TITLE
Remove "Senior Organizer" membership class

### ISSUE THREAD

**Issue by mdempsky** [dxe/adb#85]
Development committee wants to eliminate this distinction.

**Comment by jakehobbs** [comment]
Done.

- removed SO prospects & development pages from menu header
- removed handlers from the above 2 pages from main.go
- removed SO from front end (activist.vue)
- removed all SO related things from activist model
- removed columns from db: date_senior_organizer, prospect_senior_organizer
- removed word "senior" from comment in mailinglist sync
- removed SO references from power.go (although not sure if this is still used)
- updated index.go for members page
- changed levels of existing activists in prod
- removed colums from prod db: propsect_senior_organizer, so_auth, so_core, so_agreement, so_training, so_quiz, so_connector, so_onboarding
- tested

Commit: https://github.com/dxe/adb/commit/d216619f0e60663cb495e8fdd3550d852e23c3c3
